spring:
  profiles:
    active: local
  cloud:
    aws:
      s3:
        enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500

  security:
    oauth2:
      kakao:
        public-key-url: https://kauth.kakao.com/.well-known/jwks.json
        iss: https://kauth.kakao.com
        app-key: ${KAKAO_APP_KEY}


jwt:
  secret: ${JWT_SECRET}
  time:
    access: 3600000      # 1 hour (ms)
    refresh: 2592000000  # 30 days (ms)

s3:
  bucket: ${AWS_BUCKET}
  region: ap-northeast-2
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  base-prefix: home-1/cam-frontdoor
